let _stds = {
  success: true,
  allAttendance: [
    {
      name: "AASHUTOSH ADHIKARI",
      username: "78csi01-tic",
      studentId: "",
      contact: "9865011833",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "AAYUSH MAN SINGH",
      username: "78csi02-tic",
      studentId: "",
      contact: "9828571480",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "ABISHEK TIWARI",
      username: "78csi03-tic",
      studentId: "",
      contact: "9742555741",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "ANUP ADHIKARI",
      username: "78csi04-tic",
      studentId: "",
      contact: "9845237788",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "APEKSHYA LAMICHHANE",
      username: "78csi05-tic",
      studentId: "",
      contact: "9865498566",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "ARJUN LAMA",
      username: "78csi06-tic",
      studentId: "",
      contact: "9843584542",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "ASHWINA SEDHAIN",
      username: "78csi07-tic",
      studentId: "",
      contact: "9865558891",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "ASMITA MOKTAN",
      username: "78csi08-tic",
      studentId: "",
      contact: "9808275923",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "AVISEK PATHAK",
      username: "78csi09-tic",
      studentId: "",
      contact: "9823011780",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "BIBEK SHRESTHA",
      username: "78csi10-tic",
      studentId: "",
      contact: "9813637091",
      presentDays: 0,
      absentDays: 2,
      totalDays: 2,
      percentage: 0,
    },
    {
      name: "BIPIN SAUD",
      username: "78csi11-tic",
      studentId: "",
      contact: "9865678150",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "BISHAL KUNWAR",
      username: "78csi12-tic",
      studentId: "",
      contact: "9862469568",
      presentDays: 1,
      absentDays: 1,
      totalDays: 2,
      percentage: 50,
    },
    {
      name: "DIPSHIKHA DC",
      username: "78csi13-tic",
      studentId: "",
      contact: "9822599815",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "DIWASH POKHREL",
      username: "78csi14-tic",
      studentId: "",
      contact: "9825990806",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "KAUSHAL PURI",
      username: "78csi16-tic",
      studentId: "",
      contact: "9861058751",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "KISHOR UPADHYAYA",
      username: "78csi17-tic",
      studentId: "",
      contact: "9867311893",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "KONITH THAPA",
      username: "78csi18-tic",
      studentId: "",
      contact: "9825133588",
      presentDays: 1,
      absentDays: 1,
      totalDays: 2,
      percentage: 50,
    },
    {
      name: "KUSUM ADHIKARI",
      username: "78csi19-tic",
      studentId: "",
      contact: "9869068767",
      presentDays: 1,
      absentDays: 1,
      totalDays: 2,
      percentage: 50,
    },
    {
      name: "MEDHA UPADHAYAY",
      username: "78csi20-tic",
      studentId: "",
      contact: "9841321846",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "MEGHA NAYABANIYA",
      username: "78csi21-tic",
      studentId: "",
      contact: "9821844428",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "MILAN KC",
      username: "78csi22-tic",
      studentId: "",
      contact: "9849295061",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "MIRAJ ARYAL",
      username: "78csi23-tic",
      studentId: "",
      contact: "9840030664",
      presentDays: 0,
      absentDays: 2,
      totalDays: 2,
      percentage: 0,
    },
    {
      name: "MONIKA SAH",
      username: "78csi24-tic",
      studentId: "",
      contact: "9824971474",
      presentDays: 1,
      absentDays: 1,
      totalDays: 2,
      percentage: 50,
    },
    {
      name: "MONU SIDDHIQUE",
      username: "78csi25-tic",
      studentId: "",
      contact: "9800564411",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "NABIN KATWAL",
      username: "78csi26-tic",
      studentId: "",
      contact: "9861709340",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "NISHAN KHAREL",
      username: "78csi27-tic",
      studentId: "",
      contact: "9862993796",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "PEMA NAMGUR TAMANG",
      username: "78csi28-tic",
      studentId: "",
      contact: "9844257555",
      presentDays: 1,
      absentDays: 1,
      totalDays: 2,
      percentage: 50,
    },
    {
      name: "POOJASHREE KAINI",
      username: "78csi29-tic",
      studentId: "",
      contact: "9861448602",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "PRASUN DAHAL",
      username: "78csi30-tic",
      studentId: "",
      contact: "9824381791",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "RABNAM ADHIKARI",
      username: "78csi31-tic",
      studentId: "",
      contact: "9842566087",
      presentDays: 1,
      absentDays: 1,
      totalDays: 2,
      percentage: 50,
    },
    {
      name: "REUEL RAI",
      username: "78csi32-tic",
      studentId: "",
      contact: "9823281351",
      presentDays: 0,
      absentDays: 2,
      totalDays: 2,
      percentage: 0,
    },
    {
      name: "RIZAN ADHIKARI",
      username: "78csi33-tic",
      studentId: "",
      contact: "9809226481",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "ROHAN SHRESTHA",
      username: "78csi34-tic",
      studentId: "",
      contact: "9851196558",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "RUP JUNG MALLA",
      username: "78csi35-tic",
      studentId: "",
      contact: "9842288555",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "SABIN DHUNGEL",
      username: "78csi36-tic",
      studentId: "",
      contact: "9748275853",
      presentDays: 1,
      absentDays: 1,
      totalDays: 2,
      percentage: 50,
    },
    {
      name: "SAVYATA BHATTARAI",
      username: "78csi37-tic",
      studentId: "",
      contact: "9862581468",
      presentDays: 1,
      absentDays: 1,
      totalDays: 2,
      percentage: 50,
    },
    {
      name: "SITAL BIRKATTA",
      username: "78csi38-tic",
      studentId: "",
      contact: "9867786644",
      presentDays: 1,
      absentDays: 1,
      totalDays: 2,
      percentage: 50,
    },
    {
      name: "SUBODH RAJ SAH",
      username: "78csi39-tic",
      studentId: "",
      contact: "9825761249",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "SUJITA GHALN",
      username: "78csi40-tic",
      studentId: "",
      contact: "9848069087",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
    {
      name: "SUMIT SAIJU",
      username: "78csi42-tic",
      studentId: "",
      contact: "9823586959",
      presentDays: 0,
      absentDays: 2,
      totalDays: 2,
      percentage: 0,
    },
    {
      name: "SUMIT KUMAR SHRESTHA",
      username: "78csi41-tic",
      studentId: "",
      contact: "9842524266",
      presentDays: 2,
      absentDays: 0,
      totalDays: 2,
      percentage: 100,
    },
  ],
};
